### ISSUE TITLE
is onPress memoized?

### ISSUE THREAD

**Issue by ansh** [rcaferati/react-native-really-awesome-button#102]
Is the onPress prop memoized? Because if it is, there is an issue since I am using state in onPress and it using the wrong state.

Using Expo SDK 46

It seems like `onPressIn` works because it is directly being passed into the component, but ideally I would like to use `onPress` as it is significantly better UX.

Here is a reproducible demo: https://snack.expo.dev/@anshnanda/awesomebutton-not-working

**Comment by ansh** [comment]
I’m using EXPO SDK 46

**Comment by ansh** [comment]
@rcaferati Is this a bug?

**Comment by ansh** [comment]
It seems like `onPressIn` works because it is directly being passed into the component

**Comment by ansh** [comment]
Here is a reproducible demo: https://snack.expo.dev/@anshnanda/awesomebutton-not-working

**Comment by MonchiLin** [comment]
Same issue.

**Comment by ansh** [comment]
I have reached a solution via the help of StackOverflow: https://stackoverflow.com/questions/74297972/react-native-really-awesome-button-onpress-does-not-update-function-when-state-c

However, it is clear that this bug needs to be addressed in the repository.

@rcaferati

**Comment by eeshankeni** [comment]
Can confirm this bug exists and needs to be fixed. It seems to not be present in the release version

**Comment by ansh** [comment]
@eeshankeni It is present in the release version. Check out my demo: https://snack.expo.dev/@anshnanda/awesomebutton-not-working

**Comment by eeshankeni** [comment]
Weird, I tried to toggle the button's colour between two options using a state. It worked fine in the release but not in the latest version.

**Comment by ansh** [comment]
Can you provide a demo on Snack or a repo/gist? @eeshankeni

**Comment by septpointdeux** [comment]
I confirm that the bug is present and it is quite embarassing since we can not use the base functionnality of a button ... "OnPress" playing with some states, which is quite a "basic" for a button

**Comment by septpointdeux** [comment]
@awreese Thx i effectively follow your advises on SO. I tried to push to github but it seem i am not authorized to create a branch on the repo

`git  push -u -f origin fix/102-is-onpress-memoized 
ERROR: Permission to rcaferati/react-native-really-awesome-button.git denied to septpointdeux.
`

**Comment by ansh** [comment]
It has been almost a month, with a perfectly good PR created, and the maintainer of this package has not even responded. I have emailed him and he has seen the email many times and yet is probably too busy to maintain this.

So, I have forked the package, cleaned up the code, updated the dependencies, and published it under `react-native-raised-button` on NPM. 

Please find it here https://www.npmjs.com/package/react-native-raised-button?activeTab=readme
and here https://github.com/ansh/react-native-raised-button

Looking forward to your contributions @septpointdeux and @awreese

**Comment by eeshankeni** [comment]
Hey @ansh 
Thanks for your fork, I've noticed that it too has a the same onPress bug as before and the color of the button does not change with every onPress.

Do check out my expo snack https://snack.expo.dev/@esean_keni/8465d3
Notice how the button changes colour only after multiple attempts. When it should instead be changing with every press. 
Thank you!

**Comment by ansh** [comment]
@eeshankeni I have debugged your Snack and it seems like there is *another* bug in the original react-native-really-awesome-button package! This is actually absurd. I regret using this package now.

But in any case, the simplest fix is not pressing the button back-to-back. If you wait 1-2 seconds between pressing the button, the color changes every time. However, if you press the button in rapid succession, the color doesn't change and it doesn't register the new state. Not sure why this happening (maybe @awreese and @septpointdeux can take another look).

**Comment by eeshankeni** [comment]
@ansh damn this package seems more trouble than its worth. Which is unfortunate cause its really rather good

**Comment by Darren120** [comment]
is the dev dead?

**Comment by ansh** [comment]
This has been fixed in #108

**Comment by ansh** [comment]
However, since the original dev is not active, I made a fork that works better and will be maintained:
https://github.com/ansh/react-native-raised-button

All done in accordance with the MIT license
