### ISSUE TITLE
How to stop Progress Animation?

### ISSUE THREAD

**Issue by seebi98** [rcaferati/react-native-really-awesome-button#11]
When i click the button the animation start the problem is  that its continue  without stopping after a while?

**Comment by rcaferati** [comment]
The `onPress` function receives back a `next` method as the first argument. Just call it whenever you are done with the progress state. You can check the progress docs [here](https://github.com/rcaferati/react-native-really-awesome-button#progress).

**Comment by seebi98** [comment]
its didn't solved  i used the button to go from one screen  to another, but when i return back to the same screen its still continues to animate without stopping??

**Comment by rcaferati** [comment]
@seebi98 if it's an instantaneous action where you're not doing anything async, I wouldn't use the progress flag. Can you show me a code snippet or walk me through the stages?

**Comment by fbonesso** [comment]
I'm facing the same error.

Here is my code snippet:

`<AwesomeButtonRick
         progress
         raiseLevel={2}
         width={65}
         height={40}
         borderRadius={5}
         onPress={(next) => { this._onSearch(next); }}
/>`

`_onSearch(next) {
    // Some fetch statement

    next();
  }`

**Comment by seebi98** [comment]
Thanks rcaferati.
I solved it.
I appreciate your work ,once again thanks a lot.

**Comment by fbonesso** [comment]
Hi @seebi98, how did you solve this problem? Thanks!

**Comment by seebi98** [comment]
> Hi @seebi98, how did you solve this problem? Thanks!
I solved it using  the docs that @rcaferati  has mentioned.

**Comment by seebi98** [comment]
i'm closing the issue bcoz the answer was already in docs.

**Comment by rcaferati** [comment]
@seebi98 thanks o/

@fbonesso it could be that you're calling `next` on the same js loop without performing any async tasks. I found a bug related to that, I'm releasing a patch that fixes it.

**Comment by rcaferati** [comment]
@fbonesso fixed on `v1.4.0`

**Comment by seebi98** [comment]
> @fbonesso fixed on `v1.4.0`
I am also facing  the same problem of @fbonesso 
it's didn't  stop progress , if stay on the same screen?
does its fixed in new version??
