### ISSUE TITLE
the onPress function gets invoked just when the button is touched

### ISSUE THREAD

**Issue by mahdinba97** [rcaferati/react-native-really-awesome-button#13]
Hi. My problem is that when I touch the button, it invokes the function but I need the function to get invoked after the user is done holding the button. Any solutions?

**Comment by mahdinba97** [comment]
It seems that the 1.4.x versions got this problem. I fixed it with rolling back to 1.3.1.

**Comment by rcaferati** [comment]
@mahdinba97 I'm looking into it

**Comment by rcaferati** [comment]
@mahdinba97 Fixed on `v1.4.2`, thanks for pointing it out

**Comment by hevertoncastro** [comment]
I'm using the version 1.4.2 with a similar problem:

The button is inside a `ScrollView`, and it fires the `onPress` function when I just Scroll through the view (when the gesture starts from the button).
