### ISSUE TITLE
Does it support non-expo ?

### ISSUE THREAD

**Issue by manojkumawat003** [rcaferati/react-native-really-awesome-button#15]

**Comment by rcaferati** [comment]
@manojkumawat003 Sure! I've just used `Expo` for the example to simplify the distribution layer of the testing app.

**Comment by shashank-shark** [comment]
Sir I am your BIG FAN. We are both common in Facebook React Native Developers community. I went through your websites and they are awesome and sure your work wanted a **WEB OSCAR.**

**Comment by manojkumawat003** [comment]
Will it support react-native cli too?

**Comment by rcaferati** [comment]
@manojkumawat003 Yes, it also works with RN's `cli`

**Comment by rcaferati** [comment]
@shashank-shark thank you o/

**Comment by manojkumawat003** [comment]
@rcaferati  thanks!!! and great work!!
