### ISSUE TITLE
Button onPress gets delayed by animation

### ISSUE THREAD

**Issue by RodPin** [rcaferati/react-native-really-awesome-button#16]
I think the animation is postponing the onPress. Im doing a simple alert and it takes like 0.5 second for the alert appear before i click the button.Is there a way to make it quicker?why is it happening?your button on expo seems quicker

here is a gif of what's happening
https://gyazo.com/21e978e2c26554e800cf2f4c0fe32ea3

**Comment by cargallo** [comment]
The onPress event is dispached when you release the button. Don't know why in your gif the button is released so late
