### ISSUE TITLE
Question - textFamily

### ISSUE THREAD

**Issue by cargallo** [rcaferati/react-native-really-awesome-button#19]
Hi, nice buttons really helpfull! I've a question. How can I set the textFamily? I've tried               textFamily={Fonts.type.rock} where Fonts.type.rock returns a custom font that I've linked. The font is working in other View. Thanks in advance!

**Comment by SimenB** [comment]
`textFontFamily` according to the implementation: https://github.com/rcaferati/react-native-really-awesome-button/blob/ae292a2f1b739126d2f955d5aab863632e705d67/src/styles.js#L44

Seems like an error in the docs

**Comment by cargallo** [comment]
Thanks @SimenB

**Comment by rcaferati** [comment]
Fixed it there. Thanks both @cargallo @SimenB 🙌🏻
