### ISSUE TITLE
The onPress function gets invoked when you scroll through it

### ISSUE THREAD

**Issue by albertgranados** [rcaferati/react-native-really-awesome-button#20]
If the button is inside a ScrollView, it invokes the onPress function just scrolling through the view when the gesture starts from the button. It is like when you touch and move, it acts like touch and release. Any idea on how to solve it?

![20190423_030821](https://user-images.githubusercontent.com/10212923/56544671-7630cf00-6575-11e9-8cd4-70cac9cfa70a.gif)

**Comment by mmartineeez** [comment]
same issue here :/

**Comment by mmartineeez** [comment]
I fixed it with this

`var drag = false;  // declare this whereever you want
        <ScrollView
          onScrollBeginDrag={() => {
            drag = true;
          }}
          onScrollEndDrag={() => {
            drag = false;
          }}
        >
<AwesomeButton onPress={() => {
                if ( !drag ) {
                 // your code
                }
              }}
/>
</ScrollView>`

**Comment by albertgranados** [comment]
> I fixed it with this
> 
> ```
> var drag = false;  // declare this whereever you want
> <ScrollView
>           onScrollBeginDrag={() => {
>             drag = true;
>           }}
>           onScrollEndDrag={() => {
>             drag = false;
>           }}
>         >
> <AwesomeButton 
> onPress={() => {
>       if ( !drag ) {
>           // your code
>        }
>    }}
> />
> </ScrollView>
> ```

It works! Thank you! 🎉

**Comment by SimenB** [comment]
Still a bug, no? You shouldn't have to deal with it in your own code

**Comment by albertgranados** [comment]
> Still a bug, no? You shouldn't have to deal with it in your own code

You are right. Issue reopened.

**Comment by rcaferati** [comment]
Hey guys, thanks for raising this. All good on `v1.5.0`

**Comment by coldSeattle** [comment]
the same issue (

**Comment by coldSeattle** [comment]
not working
var drag = false;  // declare this whereever you want
<ScrollView
          onScrollBeginDrag={() => {
            drag = true;
          }}
          onScrollEndDrag={() => {
            drag = false;
          }}
        >
<AwesomeButton 
onPress={() => {
      if ( !drag ) {
          // your code
       }
   }}
/>
</ScrollView>
