### ISSUE TITLE
Issue with the documentation @textFamily

### ISSUE THREAD

**Issue by Monir-Shembesh** [rcaferati/react-native-really-awesome-button#21]
Hey man, I would like to first thank you for his awesome contribution! really nice keep them coming perhaps maybe next we can make icons look like these buttons! 

I would like you to fix something in the documentation please. it says to change the **fontFamily** use **textFamily** prop. However, it is actually **textFontFamily**. Also, it says its of type **number** while it is actually a **string**.

Hope this helps!

**Comment by bwold001** [comment]
I've fixed this documentation issue
