### ISSUE TITLE
More detailed styling options for creating button groups

### ISSUE THREAD

**Issue by champgm** [rcaferati/react-native-really-awesome-button#24]
I'd like to smush a couple of `react-native-really-awesome-button`s together into a row and make something like this: 
![image](https://user-images.githubusercontent.com/2091382/63042011-2153f400-be97-11e9-8ca2-edd2a100459d.png)

But the styling options don't let me control border radius by corner instead of as a whole. Using the `style` property with fields like `borderBottomRightRadius` and `borderTopRightRadius` seems to have no effect. Can you expose border corner radiuses as properties, or at least make them work via the `styles` property?

**Comment by rcaferati** [comment]
Hey @champgm, thanks for raising it. I've added the split border styling option on `v1.5.0` release. Now you can use all border radius props.
