### ISSUE TITLE
Accept relative widths (percentages)

### ISSUE THREAD

**Issue by marcbc** [rcaferati/react-native-really-awesome-button#3]
I'm testing out the component (which is great btw), but I lack support for relative widths. 

In my scenario, I'd like to be able to provide percentages in order to fill the full screen width (100%) when having a simple action button in the screen footer, or 50% if I have an accept/cancel situation.

Would you find this useful?

**Comment by trickeyd** [comment]
Agreed. It would be nice to have some sort of 'containerStyle' prop that would override the defaults rather than entering everything individually as props.

Nice little lib tho :-)

**Comment by xlcrr** [comment]
Came here looking for the same query

Then I realized you can also do something like

import { Dimensions } from 'react-native';
import AwesomeButtonRick from 'react-native-really-awesome-button/src/themes/rick';

const SCREEN_WIDTH = Dimensions.get('window').width;

```
    <AwesomeButtonRick
          type="primary"
          progress
          width={SCREEN_WIDTH}
    >Log In</AwesomeButtonRick>
```

**Comment by renanboni** [comment]
It's a really bad idea to set width={SCREEN_WIDTH * .7}, because the button is not gonna be centered...

**Comment by xlcrr** [comment]
My button is centered fine

**Comment by rcaferati** [comment]
Hey @marcbc, @xlcrr thank you both for the feedback.

I've refactored a bit the `width` strategy. We now have a `stretch` option that's used to fill the parent component you can use the parent to control the width. I might add the percentage option in the future.

**Comment by cmcleese** [comment]
Since you added a `stretch` property to have dynamic width based on the parent, it would be also really great to have the same for a **height** property. 
Something like:
- `stretchWidth`
- `stretchHeight`

That way I could have square buttons square in size.
