### ISSUE TITLE
buttons are pressed on scroll

### ISSUE THREAD

**Issue by AlirezaAzizi145** [rcaferati/react-native-really-awesome-button#32]
i have three large awesome buttons in a column. when i want to scroll the page, buttons are press and navigate to another page. this issue does not happen on react native touchable components.

**Comment by rcaferati** [comment]
Hey @AlirezaAzizi145 can you confirm which version of the button are you using on the project?

**Comment by SkyTreasure** [comment]
Hi, i am facing the same issue in 1.5.1.  I am rendering buttons in the flatlist(Scroll Disabled) and is inside the ScrollView.

**Comment by TaylorDale** [comment]
Experiencing this issue as well

**Comment by cmcleese** [comment]
Same here
