### ISSUE TITLE
The expo demo is outdated and doesn't work

### ISSUE THREAD

**Issue by raRaRa** [rcaferati/react-native-really-awesome-button#36]
Hi all.

When I try to run the Expo demo on https://expo.io/@rcaferati/react-native-really-awesome-button then I get the following message:
```
This project needs an update
This project uses Expo SDK v32.0.0. If you want to open this project, the author will need to update the project's SDK version."
```

Could the author update the project? Thanks!

**Comment by rcaferati** [comment]
Hey @raRaRa, thanks for raising it! I've updated the project, it's now accessible via the expo project page.
