### ISSUE TITLE
fontFamily or textFontFamily?

### ISSUE THREAD

**Issue by abumalick** [rcaferati/react-native-really-awesome-button#39]
Thanks for the nice button 👍 

textFontFamily prop doesn't work correctly in `1.6.0`

I think there is a confusion with `textFamily`

https://github.com/rcaferati/react-native-really-awesome-button/blob/master/src/index.js#L66

https://github.com/rcaferati/react-native-really-awesome-button/blob/master/src/index.js#L103

**Comment by rcaferati** [comment]
Hey @abumalick! Thanks for pointing it out, I've pushed a fix to `v2`.
