### ISSUE TITLE
Gradient Background?

### ISSUE THREAD

**Issue by peterchibunna** [rcaferati/react-native-really-awesome-button#6]
Thanks for this component!

However, is it possible to use a Linear Gradient background for the awesome button?

**Comment by rcaferati** [comment]
Hey @peterchibunna, thanks for the feedback. I've added it on version 1.0.0.

Just use the `ExtraContent` prop to pass a component with the gradient that fills the whole button. There's an example on the demo app using a Instagram-like gradient.

**Comment by jackyleehong** [comment]
Hello, tried with ExtraContent to add the LinearGradient, but the colors are not reflected on the button.

**Comment by peterchibunna** [comment]
@jackyleehong You need to rebuild after that. It does not update on the fly the first time, because gradient component needs to be compiled.

**Comment by jackyleehong** [comment]
Okay. Thank you

**Comment by ChiragDugar** [comment]
> @jackyleehong You need to rebuild after that. It does not update on the fly the first time, because gradient component needs to be compiled.

I tried rebuilding it, but it still doesn't reflect the changes.

**Comment by vagnerlandio** [comment]
> > @jackyleehong You need to rebuild after that. It does not update on the fly the first time, because gradient component needs to be compiled.
> 
> I tried rebuilding it, but it still doesn't reflect the changes.

Add a "style" prop on LinearGradient component with width and height values like this:

```
<LinearGradient
    style={{
        width: "100%",
        height: "100%",
    }}
/>
```
