### ISSUE TITLE
[Question] expose onPressOut method

### ISSUE THREAD

**Issue by Kiura** [rcaferati/react-native-really-awesome-button#74]
Can the `onPressOut` method be exposed?

Also any plans on adding TypeScript support?

**Comment by Kiura** [comment]
Let me clarify the issue:
1. `onPressOut` triggers even if the finger is slid out  of the button, in which case it should not trigger the `onPress` function
2. Every import of the button requires explicitly disabling the linter would be nice to have typescript support

BTW, really cool library, thx for making it

**Comment by jimdog1001** [comment]
hey! were you able to fix the slide out issue by using onPressOut? if so, mind sharing how?
